export const ecommerceAddons = [
  {
    name: "Small",
    price: "₹4,999",
    tag: "One page",
    desc: "The customer already knows the item. They scroll a single list and pay with a link.",
    bestFor: "Choose Small if the whole catalogue fits on one page.",
    features: [
      "About 50 products, no categories",
      "No search. They scroll.",
      "A UPI link. Not a payment gateway.",
      "The order is only a WhatsApp message",
      "Delivery is answered in chat",
      "No order desk for the staff",
    ],
    note: "A kirana shelf, a clinic menu, a maker with a short list. If people must browse, this is the wrong card.",
    popular: false,
  },
  {
    name: "Medium",
    price: "₹9,999",
    tag: "A shop",
    desc: "The customer has to look before they buy. Categories, a pincode before payment, and today's orders on one screen.",
    bestFor: "Choose Medium if staff currently hunt the product in chat.",
    features: [
      "About 200 products, in categories",
      "Includes Small. Do not buy both.",
      "Pincode shown before they pay",
      "Today's orders on one screen",
      "A gateway only if Growth is underneath",
      "A status template, not a typed paragraph",
    ],
    note: "This is a shop, not a longer Small. The extra ₹5,000 is the order desk and the delivery answer.",
    popular: true,
  },
  {
    name: "Expanding",
    price: "₹19,999",
    tag: "Dealer shelf",
    desc: "More than one product line, plus one path for a dealer. Not a second shop.",
    bestFor: "Several lines · one dealer enquiry · still one outlet",
    features: [
      "Includes Medium. Do not buy both.",
      "More than one product line",
      "One dealer enquiry, on your WhatsApp",
      "Order, payment, and GST invoice as one event",
      "Not a second outlet",
      "Not stock software",
    ],
    note: "Marketplaces can stay for a stranger’s first order. The dealer should not have to find you there.",
    popular: false,
  },
] as const;