export const ecommerceAddons = [
  {
    name: "Small",
    price: "₹4,999",
    tag: "Short list",
    desc: "One flat catalogue. About 50 products. A payment link, not a second checkout system.",
    bestFor: "One outlet · about 50 products · no categories",
    features: [
      "Flat list on your domain, about 50 products",
      "UPI or payment link, not a gateway",
      "In stock or out. No stock count.",
      "The order lands in WhatsApp",
      "No pincode zones",
      "Sits on Launch or Growth",
    ],
    note: "Not a store with categories. If the list is about to pass 50, take Medium instead.",
    popular: false,
  },
  {
    name: "Medium",
    price: "₹9,999",
    tag: "Order desk",
    desc: "Categories, a daily order list, and pincode notes before anyone pays.",
    bestFor: "Growing retail · about 200 products · one order screen",
    features: [
      "Includes Small. Do not buy both.",
      "Categories for about 200 products",
      "Pincode zones written before payment",
      "One daily order list for the counter",
      "Named gateway, on a Growth account",
      "WhatsApp status templates",
    ],
    note: "The gateway is Growth’s account. Medium on Launch still checks out with a payment link.",
    popular: true,
  },
  {
    name: "Expanding",
    price: "₹19,999",
    tag: "Dealer shelf",
    desc: "More than one product line, plus one path for a dealer. Not a second shop.",
    bestFor: "Several lines · one dealer enquiry · still one outlet",
    features: [
      "Includes Medium. Do not buy both.",
      "More than one product line",
      "One dealer enquiry, on your WhatsApp",
      "Order, payment, and GST invoice as one event",
      "Not a second outlet",
      "Not stock software",
    ],
    note: "Marketplaces can stay for a stranger’s first order. The dealer should not have to find you there.",
    popular: false,
  },
] as const;